[development]
shop = "Darularqamuk.myshopify.com"
api_key = "aeb49989ce766e5bba9e1e2cb855c44a"
secret = "81061afae17afd93f3f0fe39ff3d3b17"
scopes = "read_products, write_products, read_collections"
redirect_uri = "https://your-app-url/render.com/auth/callback"
